/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package pdc_lingobridge;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author sammy
 */
public class LearningMode extends javax.swing.JPanel {

    private List<String> vocabularyList;
    private int currentIndex;
    private int progress;
    private String path;

    LearningMode(String path) {
        initComponents();
        this.path = path;
        initializeLearningMode();
    }

    private void initializeLearningMode() {
        readVocabularyFromFile(this.path); 
        currentIndex = 0;
        progress = 0;
        displayNextVocabulary();
    }

    private void readVocabularyFromFile(String path) {
        CollectionsManager manager = new CollectionsManager(path);
        vocabularyList = manager.readFromFile();
    }
    
    private void displayNextVocabulary() {
        if (currentIndex < vocabularyList.size()) {
            spanishTextLabel.setText(vocabularyList.get(currentIndex).trim());
            englishTextLabel.setText((currentIndex + 1 < vocabularyList.size()) ? vocabularyList.get(currentIndex + 1).trim() : "");
            currentIndex += 2;

            progress = scoreCalculator(progress, true);
            learnProgressBar.setValue((int) ((double) progress / (vocabularyList.size() / 2) * 100));
        } else {
            spanishTextLabel.setText("Learning Complete!");
            englishTextLabel.setText("");
            continueButton.setEnabled(false);
        }
    }
    
    private int scoreCalculator(int currentScore, boolean result) {
        if (result) {
            currentScore++;
        }
        return currentScore;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();
        learnProgressBar = new javax.swing.JProgressBar();
        englishTextLabel = new javax.swing.JLabel();
        spanishTextLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(203, 226, 247));
        setPreferredSize(new java.awt.Dimension(750, 650));

        jPanel1.setBackground(new java.awt.Color(203, 226, 247));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 640));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        title.setText("Lingo Bridge");

        back.setBackground(new java.awt.Color(213, 137, 111));
        back.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        back.setText("Back");
        back.setActionCommand("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        continueButton.setBackground(new java.awt.Color(204, 226, 165));
        continueButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        learnProgressBar.setBackground(new java.awt.Color(255, 255, 153));
        learnProgressBar.setForeground(new java.awt.Color(255, 255, 153));
        learnProgressBar.setOpaque(true);

        englishTextLabel.setBackground(new java.awt.Color(204, 204, 255));
        englishTextLabel.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        englishTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        englishTextLabel.setText("English");
        englishTextLabel.setOpaque(true);

        spanishTextLabel.setBackground(new java.awt.Color(204, 204, 255));
        spanishTextLabel.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        spanishTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spanishTextLabel.setText("Spanish");
        spanishTextLabel.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 206, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(continueButton)
                            .addGap(42, 42, 42))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(learnProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(199, 199, 199)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spanishTextLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                        .addComponent(englishTextLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(back)
                .addGap(62, 62, 62)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(spanishTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(englishTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(learnProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(continueButton)
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        firePropertyChange("backToHome", false, true);

        LingoBridge.getInstance().setMainPanel(new PlayGame());
    }//GEN-LAST:event_backActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        displayNextVocabulary();
        
    }//GEN-LAST:event_continueButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel englishTextLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar learnProgressBar;
    private javax.swing.JLabel spanishTextLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
