/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pdc_lingobridge;

import javax.swing.JOptionPane;

/**
 *
 * @author sammy
 */
public class DeckSelection extends javax.swing.JPanel {

    private final String[] decks = {
        "Please select one of the following decks:",
        "(1) Los dias de la semana: The days of the week - Difficulty: Easy",
        "(2) Numeros/Numbers (1-100) - Difficulty: Moderate",
        "(3) Saludos y Despididas: Greetings and Farewells - Difficulty: Moderate",
        "(4) Introduccions: Introductions - Difficulty: Hard"
    };
    
    private String selectedDeckValue = null;
    
    public String getSelectedDeck() {
        return selectedDeckValue;
    }
    
    public boolean isSelectedDeckFirst() {
    return selectedDeckValue.equals(decks[0]);
}
    
    /**
     * Creates new form DeckSelection
     */
    public DeckSelection() {
        initComponents();
        populateComboBox();
    }

       private void populateComboBox() {
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(decks));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        confirmButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(203, 226, 247));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 650));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        title.setText("Lingo Bridge");

        back.setBackground(new java.awt.Color(213, 137, 111));
        back.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        back.setText("Back");
        back.setActionCommand("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        confirmButton1.setBackground(new java.awt.Color(204, 226, 165));
        confirmButton1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        confirmButton1.setText("Confirm");
        confirmButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(confirmButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(back)
                .addGap(62, 62, 62)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(confirmButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void backActionPerformed(java.awt.event.ActionEvent evt) {                                     
        firePropertyChange("backToHome", false, true);

        LingoBridge.getInstance().setMainPanel(new PlayGame());
    }                                    

    private void confirmButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        int selectedDeck = jComboBox1.getSelectedIndex(); // 0-based index
        if (selectedDeck != 0) {
            handleDeckSelection(selectedDeck);
        } else {
            JOptionPane.showMessageDialog(DeckSelection.this, "Please select a valid deck.");
        }
    }                                              

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
         System.out.println(jComboBox1.getSelectedItem());
    }                                          

    private void handleDeckSelection(int deck) {
    selectedDeckValue = decks[deck];
    
    // Displaying a confirmation dialog with "OK" and "Cancel" options
    int response = JOptionPane.showConfirmDialog(this, 
                                                "You selected deck: " + selectedDeckValue + ". Proceed?",
                                                "Confirm Selection",
                                                JOptionPane.OK_CANCEL_OPTION,
                                                JOptionPane.QUESTION_MESSAGE);
    
    // If the user clicks on "OK"
    if (response == JOptionPane.OK_OPTION) {
        firePropertyChange("deckSelected", false, true);
    } 
    // If the user clicks on "Cancel"
    else if (response == JOptionPane.CANCEL_OPTION) {
        // Here you can reset the combo box or navigate back to the deck selection, based on your requirements
        jComboBox1.setSelectedIndex(0); // Setting the combo box back to the default option
    }
}
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton back;
    private javax.swing.JButton confirmButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration                   
}
