/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pdc_lingobridge;

import javax.swing.JFrame;

/**
 *
 * @author celin
 */
public class PlayGame extends javax.swing.JPanel {

    /**
     * Creates new form PlayGame
     */
    public PlayGame() {
        initComponents();
        setupActionListeners();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        suggestDeckButton = new javax.swing.JButton();
        quizButton = new javax.swing.JButton();
        learnButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(203, 226, 247));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 650));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        title.setText("Lingo Bridge");

        back.setBackground(new java.awt.Color(213, 137, 111));
        back.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        back.setText("Back");
        back.setActionCommand("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        suggestDeckButton.setBackground(new java.awt.Color(204, 226, 165));
        suggestDeckButton.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        suggestDeckButton.setText("Suggest Deck");
        suggestDeckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestDeckButtonActionPerformed(evt);
            }
        });

        quizButton.setBackground(new java.awt.Color(204, 226, 165));
        quizButton.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        quizButton.setText("Quiz Mode");
        quizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizButtonActionPerformed(evt);
            }
        });

        learnButton.setBackground(new java.awt.Color(204, 226, 165));
        learnButton.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        learnButton.setText("Learning Mode");
        learnButton.setName(""); // NOI18N
        learnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(suggestDeckButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(learnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(back)
                .addGap(62, 62, 62)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(learnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(suggestDeckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
          
    private void setupActionListeners() {
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        suggestDeckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestDeckButtonActionPerformed(evt);
            }
        });

        quizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizButtonActionPerformed(evt);
            }
        });

        learnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnButtonActionPerformed(evt);
            }
        });
    }
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        firePropertyChange("backToHome", false, true);
                
        LingoBridge.getInstance().setMainPanel(new Page());
    }//GEN-LAST:event_backActionPerformed

    private void suggestDeckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestDeckButtonActionPerformed
        LingoBridge.getInstance().setMainPanel(new SuggestDeck());
    }//GEN-LAST:event_suggestDeckButtonActionPerformed

    private void quizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizButtonActionPerformed
        LingoBridge.getInstance().setMainPanel(new SelectDeck("quiz"));
        //navigateToMode("quiz");
         
    }//GEN-LAST:event_quizButtonActionPerformed

    private void learnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learnButtonActionPerformed
        LingoBridge.getInstance().setMainPanel(new SelectDeck("learn"));
        //navigateToMode("learn");
         
    }//GEN-LAST:event_learnButtonActionPerformed
   
//    private String selectDeck() {
//    // TODO: Open a deck selection interface and return the selected deck.
//    // If user cancels, return null.
//    return null; // Placeholder
//    }
    
    /*
    private void navigateToMode(String mode) {
        if (mode.equals("learn")) {
            LingoBridge.getInstance().setMainPanel(new LearningMode());
        } else if (mode.equals("quiz")) {
            LingoBridge.getInstance().setMainPanel(new QuizMode()); 
        }
    }
*/
    
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(new PlayGame());
        frame.pack();
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton learnButton;
    private javax.swing.JButton quizButton;
    private javax.swing.JButton suggestDeckButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
