/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pdc_lingobridge;

/**
 *
 * @author sammy
 */
public class SelectDeck extends javax.swing.JPanel {

    private String mode;

    public SelectDeck(String mode) {
        this.mode = mode; 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        daysButton = new javax.swing.JButton();
        greetingsButton = new javax.swing.JButton();
        introductionsButton = new javax.swing.JButton();
        numbersButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(203, 226, 247));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 650));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        title.setText("Lingo Bridge");

        back.setBackground(new java.awt.Color(213, 137, 111));
        back.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        back.setText("Back");
        back.setActionCommand("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        daysButton.setBackground(new java.awt.Color(204, 226, 165));
        daysButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        daysButton.setText("Los dias de la semana: The days of the week - Difficulty: Easy");
        daysButton.setName(""); // NOI18N
        daysButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysButtonActionPerformed(evt);
            }
        });

        greetingsButton.setBackground(new java.awt.Color(204, 226, 165));
        greetingsButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        greetingsButton.setText("Saludos y Despididas: Greetings and Farewells - Difficulty: Moderate");
        greetingsButton.setName(""); // NOI18N
        greetingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greetingsButtonActionPerformed(evt);
            }
        });

        introductionsButton.setBackground(new java.awt.Color(204, 226, 165));
        introductionsButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        introductionsButton.setText("Introduccions: Introductions - Difficulty: Hard");
        introductionsButton.setName(""); // NOI18N
        introductionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introductionsButtonActionPerformed(evt);
            }
        });

        numbersButton.setBackground(new java.awt.Color(204, 226, 165));
        numbersButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numbersButton.setText("Numeros/Numbers (1-100) - Difficulty: Moderate");
        numbersButton.setName(""); // NOI18N
        numbersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(introductionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(daysButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(greetingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numbersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(back)
                .addGap(62, 62, 62)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(daysButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numbersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(greetingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(introductionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        firePropertyChange("backToHome", false, true);

        LingoBridge.getInstance().setMainPanel(new Page());
    }//GEN-LAST:event_backActionPerformed

    private void daysButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysButtonActionPerformed
        //navigateToMode("learn");
        modeNavigator(this.mode, "./resources/DaysOfTheWeek.txt");
    }//GEN-LAST:event_daysButtonActionPerformed

    private void greetingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greetingsButtonActionPerformed
        modeNavigator(this.mode, "./resources/Greetings.txt");
    }//GEN-LAST:event_greetingsButtonActionPerformed

    private void introductionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introductionsButtonActionPerformed
        modeNavigator(this.mode, "./resources/Introductions.txt");
    }//GEN-LAST:event_introductionsButtonActionPerformed

    private void numbersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersButtonActionPerformed
        modeNavigator(this.mode, "./resources/Numbers.txt");
    }//GEN-LAST:event_numbersButtonActionPerformed

    private void modeNavigator(String mode, String filePath) {
        if (mode.equalsIgnoreCase("learn")) {
            LingoBridge.getInstance().setMainPanel(new LearningMode(filePath));
        } else if (mode.equalsIgnoreCase("quiz")) {
            LingoBridge.getInstance().setMainPanel(new QuizMode(filePath));
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton daysButton;
    private javax.swing.JButton greetingsButton;
    private javax.swing.JButton introductionsButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton numbersButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
