/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pdc_lingobridge;

import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.iapi.sql.PreparedStatement;

public class SuggestDeck extends javax.swing.JPanel {
    private DBManager dbmanager;
    
    public SuggestDeck() {
        initComponents();
        dbmanager = new DBManager();
        enterSuggest.setEnabled(false);
        populateSuggestions();
    }
    
    private void populateSuggestions() {
    DefaultTableModel model = (DefaultTableModel) suggestedTable.getModel();
    List<String[]> suggestions = dbmanager.fetchSuggestions();

    for (String[] suggestion : suggestions) {
        model.addRow(suggestion);
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        suggestTitle = new javax.swing.JLabel();
        enterSuggest = new javax.swing.JButton();
        inputSuggest = new java.awt.TextField();
        back = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        suggestedTable = new javax.swing.JTable();
        lostBack = new javax.swing.JButton();
        checkUser = new java.awt.TextField();
        checkButton = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jPanel1.setBackground(new java.awt.Color(203, 226, 247));

        jPanel2.setBackground(new java.awt.Color(203, 226, 247));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 650));

        suggestTitle.setBackground(new java.awt.Color(255, 255, 255));
        suggestTitle.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        suggestTitle.setForeground(new java.awt.Color(0, 0, 0));
        suggestTitle.setText("Suggest a Category!");

        enterSuggest.setBackground(new java.awt.Color(204, 204, 255));
        enterSuggest.setText("Enter");
        enterSuggest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterSuggestActionPerformed(evt);
            }
        });

        inputSuggest.setText("Enter your suggestion");

        back.setBackground(new java.awt.Color(204, 255, 204));
        back.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(213, 137, 111));
        exit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.setActionCommand("back");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        suggestedTable.setAutoCreateRowSorter(true);
        suggestedTable.setBackground(new java.awt.Color(255, 255, 204));
        suggestedTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suggestedTable.setForeground(new java.awt.Color(0, 0, 0));
        suggestedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Suggested Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(suggestedTable);

        lostBack.setBackground(new java.awt.Color(204, 255, 204));
        lostBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lostBack.setText("Back");
        lostBack.setActionCommand("back");
        lostBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostBackActionPerformed(evt);
            }
        });

        checkUser.setText("Enter your username");
        checkUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkUserActionPerformed(evt);
            }
        });

        checkButton.setBackground(new java.awt.Color(204, 204, 255));
        checkButton.setText("Check User");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(772, 772, 772)
                        .addComponent(back))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(suggestTitle))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(checkUser, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSuggest, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(checkButton)
                            .addGap(71, 71, 71)
                            .addComponent(enterSuggest)
                            .addGap(13, 13, 13))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lostBack)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exit))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suggestTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputSuggest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterSuggest)
                    .addComponent(checkButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(lostBack))
                .addGap(40, 40, 40)
                .addComponent(back)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(537, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enterSuggestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterSuggestActionPerformed
        // TODO add your handling code here:
        String username = checkUser.getText().trim();
    String suggestion = inputSuggest.getText().trim();

    // Check if the username and suggestion are not empty
    if (!username.isEmpty() && !suggestion.isEmpty()) {
        // Get the table's model
        DefaultTableModel model = (DefaultTableModel) suggestedTable.getModel();

        // Add a new row with the entered values
        model.addRow(new Object[]{username, suggestion});
        dbmanager.insertSuggestion(username, suggestion);


        // Optionally clear the text fields
        checkUser.setText("");
        inputSuggest.setText("");
        repaint();
    } else {
        JOptionPane.showMessageDialog(this, "Both username and suggestion must be entered", "Warning", JOptionPane.WARNING_MESSAGE);
    }

        
    }//GEN-LAST:event_enterSuggestActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        firePropertyChange("backToHome", false, true);
        LingoBridge.getInstance().setMainPanel(new Page());
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void lostBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostBackActionPerformed
        // TODO add your handling code here:
        firePropertyChange("backToHome", false, true);
        LingoBridge.getInstance().setMainPanel(new PlayGame());
    }//GEN-LAST:event_lostBackActionPerformed

    private void checkUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkUserActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // TODO add your handling code here:
        String username = checkUser.getText().trim();
        if (isUserValid(username)) {
            enterSuggest.setEnabled(true); // Enable the 'Enter' button if the user is valid
        } else {
            JOptionPane.showMessageDialog(this, "Enter a valid username", "Warning", JOptionPane.WARNING_MESSAGE);
            enterSuggest.setEnabled(false); // Keep the 'Enter' button disabled if the user is invalid
        }
    }//GEN-LAST:event_checkButtonActionPerformed

    private boolean isUserValid(String username) {
        return dbmanager.usernameExists(username);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton checkButton;
    private java.awt.TextField checkUser;
    private javax.swing.JButton enterSuggest;
    private javax.swing.JButton exit;
    private java.awt.TextField inputSuggest;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lostBack;
    private javax.swing.JLabel suggestTitle;
    private javax.swing.JTable suggestedTable;
    // End of variables declaration//GEN-END:variables

}
